### ISSUE TITLE
App forms

### ISSUE THREAD

**Issue by ashleybot** [UK-SBCoA/uniform-data-set-dotnet-web#1]
```[tasklist]
### Tasks
- [x] A1 Participant Demographics Layout
- [x] A2 Co-participant demographics Layout
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/26
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/27
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/28
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/29
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/30
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/31
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/32
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/33
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/34
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/35
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/36
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/37
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/38
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/39
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/40
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/7
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/8
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/9
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/10
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/12
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/13
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/14
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/15
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/16
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/17
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/18
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/19
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/20
```
