### ISSUE TITLE
UDS 4 UI Phase 1

### ISSUE THREAD

**Issue by ashleybot** [UK-SBCoA/uniform-data-set-dotnet-web#126]
```[tasklist]
### Tasks
- [ ] #123
- [ ] #124
- [ ] #125
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/136
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/135
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/134
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/133
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/145
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/144
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/142
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/154
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/155
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/156
```
