### ISSUE TITLE
UDS 4 UI Phase 2

### ISSUE THREAD

**Issue by ashleybot** [UK-SBCoA/uniform-data-set-dotnet-web#127]
```[tasklist]
### Tasks
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/158
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/166
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/167
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/179
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/180
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/201
```
