### ISSUE TITLE
Punchlist

### ISSUE THREAD

**Issue by ashleybot** [UK-SBCoA/uniform-data-set-dotnet-web#192]
```[tasklist]
### Tasks
- [ ] Typo in remote reason copy `RefusedInPseronVisit`
- [ ] Lookup Country codes from Appendix 1 for validating CHLDHDCTRY
- [ ] Order of race and ethnicities has changed
- [ ] More copy for other categories
- [ ] Typo in MARISTAT `Living as marrieed/domestic partner`
- [ ] Lookup occupation codes from Appendix 2 for validating PRIOCC
- [ ] Automate A1 ADI lookup
- [ ] [won't fix] Groupings of referral sources
- [ ] [won't fix] text inputs closer in proximity to radio
- [ ] Provide service method for gathering common participant demographics like DOB, race, ethnicity, years of education, highest level of education, marital status, primary residence, zip code, veteran status, primary occupation, principal referral source, referral source

- [ ] 
```

![Screenshot 2024-07-17 at 3 15 53 PM](https://github.com/user-attachments/assets/ca61040d-812b-4ec5-83a7-8020bcee2bcb)
