### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by ashleybot** [UK-SBCoA/uniform-data-set-dotnet-web#48]
```[tasklist]
### Tasks
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/49
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/50
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/51
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/79
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/80
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/81
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/82
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/83
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/84
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/85
```
