### ISSUE TITLE
App flows

### ISSUE THREAD

**Issue by ashleybot** [UK-SBCoA/uniform-data-set-dotnet-web#6]
```[tasklist]
### Tasks
- [ ] UK-SBCoA/uniform-data-set-dotnet-web#3
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/4
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/5
```
